manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: shields/kyria-rev3
      revision: petejohanson
      import: app/west.yml
  self:
    path: config
