manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
   - name: petejohanson
      url-base: https://github.com/petejohanson/zmk.git
  projects:
    - name: zmk
      remote: shields/kyria-rev3
      revision: main
      import: app/west.yml
  self:
    path: config
